name: CI / CD

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  first_interaction:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Adding this new user to Contributors...'
  contribution-guidelines-reminder:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: reminds contribution guidelines
        uses: kerhub/saved-replies@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reply: 'Hi @${{ github.event.pull_request.user.login }}, thanks for contributing to this project!'  
  prettier:
    uses: kerhub/workflows/workflows/node-job.yml@main
    with:
      command: npm run prettier --check \"**\"
  tests:
    uses: kerhub/workflows/workflows/node-job.yml@main
    with:
      command: npm run test
  contribution-greetings:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: greet the author
        uses: kerhub/saved-replies@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reply: 'Hi @${{ github.event.pull_request.user.login }}, thanks for contributing to this project!'


